### ISSUE TITLE
Homework 1

### ISSUE THREAD

**Issue by pistriak** [chygryk/maks.chygryk#1]
1. Don't use comments like this '// префиксы кодов операторов';
2. A lot of duplicated code: `while (num3 > 0) {
                sum3 = sum3 + num3 % 10;
                num3 = num3 / 10;
            }`
Just copy-pasted from some forum;
Not sure if you understand how to use loops. 
3. Read "Code Conventions for the Java Programming Language" goo.gl/b0XugS﻿ and format you code accordingly;
4. Hard to understand what is 'num ' variable for. Use more convenient names.

**Comment by chygryk** [comment]
Что мне нужно сделать с пунктом 3? Да этот участок кода скопирован с форума! Мне нужно его заменить?
A lot of duplicated code: while (num3 > 0) { sum3 = sum3 + num3 % 10; num3 = num3 / 10; } Just copy-pasted from some forum; Not sure if you understand how to use loops.
